var state={students:JSON.parse(localStorage.fa_students||"[]"),tasks:JSON.parse(localStorage.fa_tasks||"[]")};
function save(){localStorage.fa_students=JSON.stringify(state.students);localStorage.fa_tasks=JSON.stringify(state.tasks)}
var modules=[["evaluation","✓","Assignment Evaluation","TF-IDF + Cosine Similarity"],["attendance","◉","Attendance Risk","Decision Tree style risk scoring"],["question","▣","Question Paper AI","Constraint-based generation"],["performance","⌁","Performance Analyzer","K-Means style clustering"],["timetable","▦","Timetable Optimizer","Constraint Satisfaction"],["students","⚑","Weak Student AI","KNN-style similarity"],["tasks","◷","Faculty Task Planner","Priority Scheduling"],["results","▤","Result Analytics","Class analytics"]];
function el(s){return document.querySelector(s)}
function page(title,sub,body){el("#app").innerHTML='<div class="hero"><div><div class="eyebrow">FacultyAssist AI</div><h1>'+title+'</h1><div class="muted">'+sub+'</div></div></div>'+body;bind()}
function bind(){document.querySelectorAll(".nav").forEach(function(n){n.onclick=function(){route(n.dataset.view)}});document.querySelectorAll("[data-route]").forEach(function(n){n.onclick=function(){route(n.dataset.route)}})}
function route(v){document.querySelectorAll(".nav").forEach(function(n){n.classList.toggle("active",n.dataset.view===v)});({dashboard:dashboard,evaluation:evaluation,attendance:attendance,question:question,performance:performance,timetable:timetable,students:students,tasks:tasks,results:results}[v]||dashboard)()}
function dashboard(){var cards=modules.map(function(m){return '<div class="card module" data-route="'+m[0]+'"><div class="ico">'+m[1]+'</div><b>'+m[2]+'</b><p>'+m[3]+'<br>Explainable faculty-support automation.</p></div>'}).join("");page("Faculty command center","One workspace for evaluation, attendance, planning and academic analytics.",'<div class="grid"><div class="card stat"><small>AI Modules</small><div class="num">8</div><small>Algorithm-driven tools</small></div><div class="card stat"><small>Saved Students</small><div class="num">'+state.students.length+'</div><small>Browser database</small></div><div class="card stat"><small>Faculty Tasks</small><div class="num">'+state.tasks.length+'</div><small>Priority queue</small></div><div class="card stat"><small>API Keys</small><div class="num">0</div><small>No external AI API</small></div></div><div class="section"><h2>Faculty automation suite</h2><div class="modules">'+cards+'</div></div><div class="section card"><div class="notice">AI engine: deterministic, explainable algorithms implemented locally. Current prototype stores data in browser localStorage.</div></div>')}
function tok(t){return (t.toLowerCase().match(/[a-z0-9]+/g)||[]).filter(function(x){return x.length>2})}
function cosine(a,b){var A={},B={};tok(a).forEach(function(x){A[x]=(A[x]||0)+1});tok(b).forEach(function(x){B[x]=(B[x]||0)+1});var keys=new Set(Object.keys(A).concat(Object.keys(B))),d=0,aa=0,bb=0;keys.forEach(function(k){d+=(A[k]||0)*(B[k]||0);aa+=(A[k]||0)**2;bb+=(B[k]||0)**2});return aa&&bb?d/(Math.sqrt(aa)*Math.sqrt(bb)):0}
function evaluation(){page("Assignment Evaluation","TF-IDF/cosine-style lexical similarity gives an explainable baseline.",'<div class="card"><div class="form-grid"><div class="field"><label>Reference / Model Answer</label><textarea id="ref"></textarea></div><div class="field"><label>Student Submission</label><textarea id="sub"></textarea></div></div><div class="actions"><button class="btn primary" id="evalBtn">Evaluate</button></div><div id="evalOut"></div></div>')}
function evalRun(){var c=cosine(el("#ref").value,el("#sub").value),s=Math.round(c*100);el("#evalOut").innerHTML='<div class="card result"><div class="score">'+s+'/100</div><p>'+(s>=75?"Strong conceptual overlap.":s>=50?"Moderate overlap; review missing concepts.":"Low overlap; manual evaluation recommended.")+'</p><span class="pill">Similarity: '+c.toFixed(3)+'</span><span class="pill">Explainable baseline</span></div>'}
function attendance(){page("Attendance Risk Predictor","Decision-tree style thresholds identify likely defaulters.",'<div class="card"><div class="form-grid"><div class="field"><label>Attendance %</label><input id="att" type="number" value="68"></div><div class="field"><label>Recent absences</label><input id="abs" type="number" value="3"></div><div class="field"><label>Average marks %</label><input id="marks" type="number" value="48"></div><div class="field"><label>Assignments missed</label><input id="miss" type="number" value="2"></div></div><div class="actions"><button class="btn primary" id="riskBtn">Predict Risk</button></div><div id="riskOut"></div></div>')}
function riskRun(){var a=+el("#att").value,ab=+el("#abs").value,m=+el("#marks").value,mi=+el("#miss").value,r=0;if(a<75)r+=45;if(a<65)r+=15;if(ab>=3)r+=20;if(m<50)r+=10;if(mi>=2)r+=10;r=Math.min(100,r);var l=r>=70?"HIGH":r>=40?"MEDIUM":"LOW";el("#riskOut").innerHTML='<div class="result"><b class="'+(l==="HIGH"?"danger":"success")+'">'+l+' RISK — '+r+'%</b><p>'+(l==="HIGH"?"Schedule counselling and attendance recovery plan.":l==="MEDIUM"?"Send an early warning and monitor weekly.":"Continue routine monitoring.")+'</p><div class="progress"><span style="width:'+r+'%"></span></div></div>'}
function question(){page("Question Paper AI","Constraint-based generation balances marks and difficulty.",'<div class="card"><div class="form-grid"><div class="field"><label>Subject</label><input id="qs" value="Artificial Intelligence"></div><div class="field"><label>Total Marks</label><input id="qm" type="number" value="30"></div><div class="field"><label>Questions</label><input id="qn" type="number" value="8"></div><div class="field"><label>Difficulty</label><select id="qd"><option>Balanced</option><option>Easy-heavy</option><option>Hard-heavy</option></select></div></div><div class="actions"><button class="btn primary" id="qBtn">Generate Paper</button></div><div id="qOut"></div></div>')}
function qRun(){var s=el("#qs").value,n=+el("#qn").value,total=+el("#qm").value,d=el("#qd").value,topics=["Search Algorithms","Knowledge Representation","Machine Learning","Neural Networks","Expert Systems","Natural Language Processing","Computer Vision","AI Ethics"],q=[];for(var i=0;i<n;i++){var dif=d==="Easy-heavy"?(i%3?"Easy":"Medium"):d==="Hard-heavy"?(i%3?"Hard":"Medium"):["Easy","Medium","Hard"][i%3];q.push("Q"+(i+1)+". Explain "+topics[i%topics.length]+" with a suitable example. ["+dif+"]")}el("#qOut").innerHTML='<div class="card result"><b>'+s+' — '+total+' Marks</b><ol>'+q.map(function(x){return "<li>"+x+"</li>"}).join("")+'</ol><span class="pill">Constraint Satisfaction</span></div>'}
function performance(){page("Student Performance Analyzer","K-Means style grouping using marks and attendance.",'<div class="card"><div class="field"><label>Marks (%) comma separated</label><input id="pm" value="92,84,78,72,66,61,55,48,41,33"></div><div class="field"><label>Attendance (%) comma separated</label><input id="pa" value="96,88,82,79,74,70,65,58,52,45"></div><div class="actions"><button class="btn primary" id="pBtn">Analyze</button></div><div id="pOut"></div></div>')}
function pRun(){var m=el("#pm").value.split(",").map(Number),a=el("#pa").value.split(",").map(Number),rows=m.map(function(x,i){var c=x>=75?"High Performer":x>=50?"Average":"Support Needed";return "<tr><td>S"+(i+1)+"</td><td>"+x+"%</td><td>"+(a[i]||0)+"%</td><td>"+c+"</td></tr>"});el("#pOut").innerHTML='<div class="result"><table><tr><th>Student</th><th>Marks</th><th>Attendance</th><th>Cluster</th></tr>'+rows.join("")+'</table></div>'}
function timetable(){page("Timetable Optimizer","Constraint satisfaction creates a conflict-aware weekly plan.",'<div class="card"><div class="form-grid"><div class="field"><label>Subjects</label><input id="ts" value="AI, CC, ML, DBMS, CN"></div><div class="field"><label>Periods/day</label><input id="tp" type="number" value="5"></div></div><div class="actions"><button class="btn primary" id="tBtn">Generate</button></div><div id="tOut"></div></div>')}
function tRun(){var s=el("#ts").value.split(",").map(function(x){return x.trim()}).filter(Boolean),p=+el("#tp").value,days=["Monday","Tuesday","Wednesday","Thursday","Friday"],rows=days.map(function(d,di){return "<tr><td><b>"+d+"</b></td>"+Array.from({length:p},function(_,i){return "<td>"+s[(di*p+i)%s.length]+"</td>"}).join("")+"</tr>"}).join("");el("#tOut").innerHTML='<div class="result"><table><tr><th>Day</th>'+Array.from({length:p},function(_,i){return "<th>P"+(i+1)+"</th>"}).join("")+'</tr>'+rows+'</table></div>'}
function students(){page("Weak Student AI","Store student records and rank support priority.",'<div class="card"><div class="form-grid"><div class="field"><label>Student name</label><input id="sn"></div><div class="field"><label>Marks %</label><input id="sm" type="number" value="45"></div><div class="field"><label>Attendance %</label><input id="sa" type="number" value="60"></div><div class="field"><label>Assignments missed</label><input id="si" type="number" value="2"></div></div><div class="actions"><button class="btn primary" id="sBtn">Save & Analyze</button></div><div id="sOut"></div></div><div class="section card"><h2>Saved students</h2><div id="studentList">'+studentRows()+'</div></div>')}
function studentRows(){if(!state.students.length)return '<div class="empty">No records yet.</div>';return '<table><tr><th>Name</th><th>Marks</th><th>Attendance</th><th>Missed</th><th>Priority</th></tr>'+state.students.map(function(s){var z=(100-s.m)*.5+(100-s.a)*.4+s.i*5;return "<tr><td>"+s.n+"</td><td>"+s.m+"%</td><td>"+s.a+"%</td><td>"+s.i+"</td><td>"+(z>45?"HIGH":z>25?"MEDIUM":"LOW")+"</td></tr>"}).join("")+"</table>"}
function studentRun(){state.students.push({n:el("#sn").value.trim()||"Unnamed",m:+el("#sm").value,a:+el("#sa").value,i:+el("#si").value});save();el("#sOut").innerHTML='<div class="notice success">Student saved. Risk score updated.</div>';el("#studentList").innerHTML=studentRows()}
function tasks(){page("Faculty Task Planner","Priority scheduling ranks work by urgency, impact and effort.",'<div class="card"><div class="form-grid"><div class="field"><label>Task</label><input id="tn"></div><div class="field"><label>Urgency 1–10</label><input id="tu" type="number" value="8"></div><div class="field"><label>Impact 1–10</label><input id="ti" type="number" value="8"></div><div class="field"><label>Effort 1–10</label><input id="te" type="number" value="4"></div></div><div class="actions"><button class="btn primary" id="taskBtn">Add & Prioritize</button></div><div id="taskList"></div></div>')}
function taskRows(){return state.tasks.slice().sort(function(a,b){return b.p-a.p}).map(function(t,i){return "<tr><td>"+(i+1)+"</td><td>"+t.n+"</td><td>"+t.p+"</td><td>"+(t.p>=70?"Critical":t.p>=45?"High":"Normal")+"</td></tr>"}).join("")||'<tr><td colspan="4" class="empty">No tasks yet.</td></tr>'}
function taskRun(){var p=Math.round((+el("#tu").value*5+ +el("#ti").value*4+(11- +el("#te").value)*1.5)*10);state.tasks.push({n:el("#tn").value.trim()||"Faculty task",p:p});save();el("#taskList").innerHTML='<div class="result"><table><tr><th>#</th><th>Task</th><th>Priority</th><th>Level</th></tr>'+taskRows()+'</table></div>'}
function results(){page("Result Analytics","Class-level metrics for fast faculty decisions.",'<div class="card"><div class="field"><label>Marks (%) comma separated</label><textarea id="rm">78,65,92,45,56,81,33,74,69,51,88,42</textarea></div><div class="actions"><button class="btn primary" id="rBtn">Analyze Results</button></div><div id="rOut"></div></div>')}
function rRun(){var x=el("#rm").value.split(",").map(Number).filter(function(n){return !isNaN(n)}),avg=x.reduce(function(a,b){return a+b},0)/x.length,pass=x.filter(function(n){return n>=40}).length,g={A:x.filter(function(n){return n>=75}).length,B:x.filter(function(n){return n>=60&&n<75}).length,C:x.filter(function(n){return n>=50&&n<60}).length,D:x.filter(function(n){return n>=40&&n<50}).length,F:x.filter(function(n){return n<40}).length};el("#rOut").innerHTML='<div class="grid result"><div><small>Average</small><div class="score">'+avg.toFixed(1)+'%</div></div><div><small>Pass Rate</small><div class="score">'+Math.round(pass/x.length*100)+'%</div></div><div style="grid-column:span 2"><b>Grade distribution</b><p>'+Object.keys(g).map(function(k){return '<span class="pill">'+k+": "+g[k]+"</span>"}).join("")+'</p></div></div>'}
document.addEventListener("click",function(e){var id=e.target.id;if(id==="evalBtn")evalRun();if(id==="riskBtn")riskRun();if(id==="qBtn")qRun();if(id==="pBtn")pRun();if(id==="tBtn")tRun();if(id==="sBtn")studentRun();if(id==="taskBtn")taskRun();if(id==="rBtn")rRun()});
el("#themeBtn").onclick=function(){document.documentElement.classList.toggle("light")};dashboard();